packages:
  - apps/**
  - examples/**
  - packages/**
  - scripts/**

catalog:
  "@antfu/eslint-config": ^4.19.0
  "@astrojs/check": ^0.9.4
  "@astrojs/mdx": ^4.3.3
  "@astrojs/react": ^4.3.0
  "@astrojs/sitemap": ^3.4.2
  "@astrojs/vercel": ^8.2.5
  "@changesets/cli": ^2.29.5
  "@docsearch/css": ^3.9.0
  "@docsearch/react": ^3.9.0
  "@fontsource-variable/merriweather": ^5.2.4
  "@fontsource-variable/open-sans": ^5.2.6
  "@fontsource-variable/public-sans": ^5.2.6
  "@fontsource-variable/roboto-mono": ^5.2.6
  "@fontsource-variable/source-sans-3": ^5.2.8
  "@fontsource/merriweather": ^5.2.9
  "@iconify-json/material-symbols": ^1.2.30
  "@iconify/json": ^2.2.366
  "@iconify/tailwind4": ^1.0.6
  "@iconify/utils": ^2.3.0
  "@napi-rs/image": ^1.11.1
  "@playwright/test": ^1.54.2
  "@tailwindcss/forms": ^0.5.10
  "@tailwindcss/typography": 0.5.16
  "@tailwindcss/vite": ^4.1.11
  "@types/fs-extra": 11.0.1
  "@types/node": 18.16.19
  "@types/prettier": 2.7.3
  "@types/react": ^19.1.9
  "@types/react-dom": ^19.1.7
  "@types/twig": ^1.12.17
  "@vercel/analytics": ^1.5.0
  "@zag-js/anatomy": ^1.21.1
  "@zag-js/aria-hidden": ^1.21.1
  "@zag-js/core": ^1.21.1
  "@zag-js/dismissable": 1.21.1
  "@zag-js/dom-query": 1.21.1
  "@zag-js/focus-trap": ^1.21.1
  "@zag-js/popper": ^1.21.6
  "@zag-js/remove-scroll": ^1.21.1
  "@zag-js/splitter": ^1.21.1
  "@zag-js/store": ^1.21.1
  "@zag-js/types": ^1.21.1
  "@zag-js/utils": ^1.21.1
  astro: ^5.12.8
  astro-expressive-code: ^0.41.3
  astro-seo: ^0.8.4
  eslint: ^9.32.0
  find-up: 6.3.0
  fs-extra: 11.1.1
  fuse.js: ^7.1.0
  github-slugger: ^2.0.0
  nanoid: ^5.1.5
  playwright: ^1.54.2
  react: 19.1.0
  react-dom: 19.1.0
  satori: ^0.12.2
  sharp: ^0.34.3
  tailwindcss: 4.1.11
  tailwindcss-animate: ^1.0.7
  tiny-invariant: ^1.3.3
  ts-morph: 19.0.0
  ts-pattern: 5.0.3
  tsdown: ^0.12.9
  tsx: ^4.20.3
  turbo: ^2.5.5
  twig: ^1.17.1
  typescript: ^5.9.2
  vite: ^7.0.6

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - rolldown
  - sharp
