/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4f9fe9ddb2ea1e2c41e1be5910da8551)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
