name: CI

on:
  push:
    branches:
      - main
      - next
    tags:
      - "!**"
  pull_request:
    branches:
      - main
      - next

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Build packages
        run: pnpm build:packages

      - run: pnpm dlx pkg-pr-new publish ./packages/**/*

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Run ESLint
        run: pnpm lint

  typecheck:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Build packages
        run: pnpm build:packages

      - name: Run TypeScript check
        run: pnpm typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Build packages
        run: pnpm build:packages

      - name: Setup Playwright
        run: pnpm dlx playwright install --with-deps chromium

      - name: Run tests
        run: pnpm test:browser
