name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release (Beta + Latest)
    runs-on: ubuntu-latest
    if: github.repository_owner == 'jbhutch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Verify package integrity
        run: pnpm audit --audit-level high

      - name: Release (Beta + Latest)
        run: pnpm publish-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
